### ISSUE TITLE
Doctests start failing after introduction of jaraco.test

### ISSUE THREAD

**Issue by jaraco** [jaraco/jaraco.test#3]
In [jaraco.itertools](/jaraco/jaraco.itertools), the tests have started failing after adopting `jaraco.test`. 

```
jaraco.itertools master $ tox
python develop-inst-noop: /Users/jaraco/code/main/jaraco.itertools
python installed: appdirs==1.4.4,attrs==20.3.0,black==20.8b1,click==7.1.2,coverage==5.3,docutils==0.16,filelock==3.0.12,flake8==3.8.4,inflect==5.0.2,iniconfig==1.1.1,jaraco.apt==2.0,jaraco.classes==3.1.0,jaraco.collections==3.0.0,jaraco.context==3.0.0,jaraco.functools==3.0.1,-e git+gh://jaraco/jaraco.itertools@e9f23a4f1cb9002d900f07a90095fdc354c11005#egg=jaraco.itertools,jaraco.test==4.0.1,jaraco.text==3.2.0,mccabe==0.6.1,more-itertools==8.6.0,mypy==0.790,mypy-extensions==0.4.3,packaging==20.4,pathspec==0.8.1,pluggy==0.13.1,py==1.9.0,pycodestyle==2.6.0,pyflakes==2.2.0,pyparsing==2.4.7,pytest==6.1.2,pytest-black==0.3.12,pytest-checkdocs==2.1.1,pytest-flake8==1.0.6,pytz==2020.4,regex==2020.11.13,six==1.15.0,tempora==4.0.1,toml==0.10.2,typed-ast==1.4.1,typing-extensions==3.7.4.3,yg.lockfile==2.3,zc.lockfile==2.0
python run-test-pre: PYTHONHASHSEED='4015069287'
python run-test: commands[0] | pytest
======================================================= test session starts ========================================================
platform darwin -- Python 3.9.0, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
cachedir: .tox/python/.pytest_cache
rootdir: /Users/jaraco/code/main/jaraco.itertools, configfile: pytest.ini
plugins: black-0.3.12, jaraco.test-4.0.1, flake8-1.0.6, checkdocs-2.1.1
collected 44 items                                                                                                                 

setup.py .ss                                                                                                                 [  6%]
docs/conf.py ss                                                                                                              [ 11%]
jaraco/__init__.py ss                                                                                                        [ 15%]
jaraco/itertools.py ss...........F.......................                                                                    [100%]

============================================================= FAILURES =============================================================
____________________________________________ [doctest] jaraco.itertools.assert_ordered _____________________________________________
969 
970     Assert that for all items in the iterable, they're in order based on comp
971 
972     >>> list(assert_ordered(range(5)))
973     [0, 1, 2, 3, 4]
974     >>> list(assert_ordered(range(5), comp=operator.ge))
Differences (unified diff with -expected +actual):
    @@ -1,3 +1,10 @@
     Traceback (most recent call last):
    -...
    +  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
    +    exec(compile(example.source, filename, "single",
    +  File "<doctest jaraco.itertools.assert_ordered[1]>", line 1, in <module>
    +    list(assert_ordered(range(5), comp=operator.ge))
    +  File "/Users/jaraco/code/main/jaraco.itertools/jaraco/itertools.py", line 990, in assert_ordered
    +    assert comp(*keyed), err_tmpl.format(**locals())
     AssertionError: 0 < 1
    +assert False
    + +  where False = <built-in function ge>(*(0, 1))

/Users/jaraco/code/main/jaraco.itertools/jaraco/itertools.py:974: DocTestFailure
===================================================== short test summary info ======================================================
FAILED jaraco/itertools.py::jaraco.itertools.assert_ordered
============================================= 1 failed, 35 passed, 8 skipped in 0.61s ==============================================
ERROR: InvocationError for command /Users/jaraco/code/main/jaraco.itertools/.tox/python/bin/pytest (exited with code 1)
_____________________________________________________________ summary ______________________________________________________________
ERROR:   python: commands failed
```

Removing `jaraco.test` but enabling the plugins explicitly somehow allows the tests to pass:

```
jaraco.itertools master $ .tox/python/bin/pip uninstall -y jaraco.test
Found existing installation: jaraco.test 4.0.1
Uninstalling jaraco.test-4.0.1:
  Successfully uninstalled jaraco.test-4.0.1
jaraco.itertools master $ tox -- --flake8 --black --mypy --cov
python develop-inst-noop: /Users/jaraco/code/main/jaraco.itertools
python installed: appdirs==1.4.4,attrs==20.3.0,black==20.8b1,click==7.1.2,coverage==5.3,docutils==0.16,filelock==3.0.12,flake8==3.8.4,inflect==5.0.2,iniconfig==1.1.1,jaraco.apt==2.0,jaraco.classes==3.1.0,jaraco.collections==3.0.0,jaraco.context==3.0.0,jaraco.functools==3.0.1,-e git+gh://jaraco/jaraco.itertools@e9f23a4f1cb9002d900f07a90095fdc354c11005#egg=jaraco.itertools,jaraco.text==3.2.0,mccabe==0.6.1,more-itertools==8.6.0,mypy==0.790,mypy-extensions==0.4.3,packaging==20.4,pathspec==0.8.1,pluggy==0.13.1,py==1.9.0,pycodestyle==2.6.0,pyflakes==2.2.0,pyparsing==2.4.7,pytest==6.1.2,pytest-black==0.3.12,pytest-checkdocs==2.1.1,pytest-cov==2.10.1,pytest-flake8==1.0.6,pytest-mypy==0.8.0,pytz==2020.4,regex==2020.11.13,six==1.15.0,tempora==4.0.1,toml==0.10.2,typed-ast==1.4.1,typing-extensions==3.7.4.3,yg.lockfile==2.3,zc.lockfile==2.0
python run-test-pre: PYTHONHASHSEED='562560314'
python run-test: commands[0] | pytest --flake8 --black --mypy --cov
======================================================= test session starts ========================================================
platform darwin -- Python 3.9.0, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
cachedir: .tox/python/.pytest_cache
rootdir: /Users/jaraco/code/main/jaraco.itertools, configfile: pytest.ini
plugins: mypy-0.8.0, black-0.3.12, flake8-1.0.6, checkdocs-2.1.1, cov-2.10.1
collected 49 items                                                                                                                 

setup.py .ss..                                                                                                               [ 10%]
docs/conf.py ss.                                                                                                             [ 16%]
jaraco/__init__.py ss.                                                                                                       [ 22%]
jaraco/itertools.py ss....................................                                                                   [100%]

---------- coverage: platform darwin, python 3.9.0-final-0 -----------
Name                  Stmts   Miss  Cover   Missing
---------------------------------------------------
docs/conf.py              3      0   100%
jaraco/__init__.py        1      0   100%
jaraco/itertools.py     344     29    92%   37-39, 140-141, 222, 230, 262, 272, 307, 337, 394-395, 427, 580, 760-762, 765-767, 799-805, 894-895
---------------------------------------------------
TOTAL                   348     29    92%

=============================================================== mypy ===============================================================

Success: no issues found in 4 source files
================================================== 41 passed, 8 skipped in 1.03s ===================================================
_____________________________________________________________ summary ______________________________________________________________
  python: commands succeeded
  congratulations :)
```

**Comment by jaraco** [comment]
Disabling the plugin with `-p 'no:plugin-enabled options'` doesn't help. Neither does removing all of the functionality of that plugin (truncating `jaraco.test.pytest.enabler`). Removing the plugin entry point, however, does alleviate the failure:

```
jaraco.test master $ git diff
diff --git a/setup.cfg b/setup.cfg
index fc006be..5f92da2 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -49,5 +49,3 @@ docs =
        # local
 
 [options.entry_points]
-pytest11 =
-       plugin-enabled options = jaraco.test.pytest.enabler
```

I'm now suspecting that something about how plugins are initialized affects the way the `jaraco` namespace is treated for assert rewrites or doctests (or both), and the presence of any `jaraco.*` in a plugin is somehow breaking assumptions.

**Comment by jaraco** [comment]
This issue was side-stepped by moving the functionality out of the jaraco namespace. There's still a lot of work to do in pytest to support namespace packages.
